name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts


      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "

          echo 'Connected to EC2'

          cd ~/ci-cd_demo &&

          echo 'Pulling latest code' &&
          git pull origin main &&

          echo 'Installing backend dependencies' &&
          cd backend &&
          npm install &&
          pm2 restart backend &&

          echo 'Building frontend' &&
          cd ../frontend &&
          npm install &&
          npm run build &&

          echo 'Updating nginx files' &&
          sudo rm -rf /var/www/html/* &&
          sudo cp -r dist/* /var/www/html/ &&

          echo 'Restarting nginx' &&
          sudo systemctl restart nginx

          "